Add methods for comment creation
specs-feup/clava pull request #38
Opened 2021-08-08 14:39 UTC by Sleepy105

Adds method for creating a comment joinpoint
Adds method for converting any joinpoint into a comment

2021-08-08 14:49 UTC, Sleepy105 commented
I have no idea how to add a method to `AstFactory` that makes comment type joinpoints.
Once that is done, it can be integrated into the `ClavaJoinPoints.comment` method to complete this PR.

2021-08-08 16:08 UTC, joaobispo requested changes

2021-08-08 16:08 UTC, joaobispo commented on ClavaLaraApi/src-lara-clava/clava/clava/ClavaJoinPoints.lara
> +    );
```suggestion
```

2021-08-08 16:08 UTC, joaobispo commented on ClavaLaraApi/src-lara-clava/clava/clava/ClavaJoinPoints.lara
> +    );
I've added a global action $jp.toComment, with overloads .toComment(prefix) and toComment(prefix, suffix).

2022-02-07 08:47 UTC, lm-sousa commented
Fixed by adding ```toComment``` method to jointpoints.

2022-02-07 08:47 UTC, closed without merging